export const FETCH_LISTINGS = 'app/HomePage/FETCH_LISTINGS';
export const LISTINGS_LOADED = 'app/HomePage/LISTINGS_LOADED';
export const FETCH_AUTH_PROVIDERS = 'FETCH_AUTH_PROVIDERS';
export const AUTH_PROVIDERS_LOADED = 'AUTH_PROVIDERS_LOADED';
export const FETCH_AUTH_SESSION = 'FETCH_AUTH_SESSION';
export const AUTH_SESSION_LOADED = 'AUTH_SESSION_LOADED';
